@startuml Library
!theme vibrant

participant Participant 
actor       Member     
actor       Librarian  
entity "Borrowing System" as BS
entity      Book

== Borrowing a Book ==

Member->Librarian: Borrow book request
activate Member
activate Librarian
Librarian->BS: Check availability of requested book
activate BS
BS->Book: Is the book available?
activate Book
Book --> BS: Available/Not Available
deactivate Book
BS-->Librarian: Display availability message
deactivate BS
Librarian-->Member: Notify borrowing result

alt Book Available
    
    Librarian->BS: Create borrowing request
    activate BS
    BS->Book: Update book status to "Borrowed"
    BS->Librarian: Record member borrowing
    deactivate BS
    Librarian->Member: Give book

else Book not available
    opt Member chooses to reserve unavailable book
        Member->Librarian: Request to reserve book
        activate BS
        Librarian->BS: Create reservation
        BS->Book: Update book status to "Reserved"
        BS-->Librarian: Display reservation confirmation
        deactivate BS
        Librarian-->Member: Confirm reservation


end

end

deactivate Librarian
deactivate Member

== Returning a Book ==

Member->Librarian: Return book
activate Member
activate Librarian
Librarian->BS: Record member return
activate BS
BS->Book: Update book status as "Available"
BS-->Librarian: Display return confirmation 
deactivate BS
Librarian-->Member: Confirm return success
deactivate Librarian
deactivate Member

@enduml
